/**
 * Command Codes are used to send commands to the MeshCore device from the app.
 * https://github.com/meshcore-dev/MeshCore/wiki/Companion-Radio-Protocol#app-commandsrequests
 */
export enum CommandCode {
    APP_START = 1,
    SEND_TXT_MSG = 2,
    SEND_CHANNEL_TXT_MSG = 3,
    GET_CONTACTS = 4,
    GET_DEVICE_TIME = 5,
    SET_DEVICE_TIME = 6,
    SEND_SELF_ADVERT = 7,
    SET_ADVERT_NAME = 8,
    ADD_UPDATE_CONTACT = 9,
    SYNC_NEXT_MESSAGE = 10,
    SET_RADIO_PARAMS = 11,
    SET_RADIO_TX_POWER = 12,
    RESET_PATH = 13,
    SET_ADVERT_LATLON = 14,
    REMOVE_CONTACT = 15,
    SHARE_CONTACT = 16,
    EXPORT_CONTACT = 17,
    IMPORT_CONTACT = 18,
    REBOOT = 19,
    GET_BATT_AND_STORAGE = 20,
    SET_TUNING_PARAMS = 21,
    DEVICE_QUERY = 22,
    SEND_RAW_DATA = 25,
    SEND_LOGIN = 26,
    SEND_STATUS_REQ = 27,
    SEND_TRACE_PATH = 36,
    SET_OTHER_PARAMS = 38,
    SEND_TELEMETRY_REQ = 39,
    GET_CUSTOM_VARS = 40,
    SET_CUSTOM_VAR = 41,
    GET_ADVERT_PATH = 42,
    GET_TUNING_PARAMS = 43,
    SEND_BINARY_REQ = 50,
    FACTORY_RESET = 51,
    SEND_CONTROL_DATA = 55,
    GET_STATS = 56,
}
